name: ci

concurrency:
  group: ci-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Lint
        run: make lint

  # lint:
  #   name: TFLint Inspection
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v6

  #     - name: Setup TFLint
  #       uses: terraform-linters/setup-tflint@v6

  #     - name: Show version
  #       run: tflint --version

  #     - name: Init TFLint
  #       run: tflint --init

  #     - name: Run TFLint
  #       run: tflint
